# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: DEPS
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: <%= ENV['DB_ENDPOINT']>

development:
  <<: *default
  database: DEPS_devlopment

test:
  <<: *default
  database: DEPS_test

production:
  <<: *default
  database: DEPS_production
