
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: DEPS
  username: grinch1225
  password: 55452yxr
  socket: /tmp/mysql.sock
  host: deps-mysql.cycmh4wlvook.ap-northeast-1.rds.amazonaws.com

development:
  <<: *default
  database: DEPS_development

test:
  <<: *default
  database: DEPS_test

production:
  <<: *default
  database: DEPS_production
