default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: db/development.development

test:
  <<: *default
  database: db/test.test

production:
  <<: *default
  database: db/production.production